### PR TITLE
Create new xSRE object type

### PR DESCRIPTION
**Pull request by mattharris5**
The SRE working group proposed the creation of a new xSRE object that aligns more closely with xStudent and the other xPress objects. The previous SRE object used CEDS names and was misaligned with the rest of the spec. The introduction of xPress gives us an opportunity to align the SRE with the new objects, which also eases a developer's potential transition between the two, enabling easier adoption. xSRE extends the xStudent base type, adding significant detail suitable for transferring a full student record in a single, relatively flattened object.

### CODE REVIEW

**Comment by mattharris5** [comment]
Please don't merge this yet!

**Comment by 4pins** [comment]
Are we ready?

**Comment by NathanClinton** [comment]
I'm done with my parts, but I'm not sure if Matt has finished the remerge yet.

**Comment by mattharris5** [comment]
Nope, I've been slammed with meetings! Sorry. soon.

**Comment by 4pins** [comment]
Okay, standing by.
FYI:  "We can’t automatically merge this pull request. "

**Comment by 4pins** [comment]
FYI:  @vinceparedes is putting together a pull request of his latest work now.

**Comment by 4pins** [comment]
FYI:  Just merged Vince's latest work into master.

**Comment by mattharris5** [comment]
Getting closer. But still having an issue merging in the correct xPress object changes. (This is all due to the fact that we started from a different base unfortunately)

**Comment by mattharris5** [comment]
The changes were mergeable until the latest push to master. Not sure why it won't merge now. Working on it.

**Comment by mattharris5** [comment]
OK @4pins it looks like we're ready to go.

**Pull request merged**
